"C:/Program Files (x86)/MSBuild/14.0/Bin/msbuild.exe" fltk/build/fltk.sln /t:clean
"C:/Program Files (x86)/MSBuild/14.0/Bin/msbuild.exe" fltk/build/fltk.sln /p:OutDir=../../../fltk_nuget/lib/native/v120/windesktop/msvcstl/Win32/Debug/mt/ /p:Configuration=Debug /p:Platform=Win32 /p:PlatformToolset=v120 /p:RuntimeLibrary=MultiThreadedDebug
"C:/Program Files (x86)/MSBuild/14.0/Bin/msbuild.exe" fltk/build/fltk.sln /p:OutDir=../../../fltk_nuget/lib/native/v120/windesktop/msvcstl/Win32/Debug/md/ /p:Configuration=Debug /p:Platform=Win32 /p:PlatformToolset=v120 /p:RuntimeLibrary=MultiThreadedDebugDLL
"C:/Program Files (x86)/MSBuild/14.0/Bin/msbuild.exe" fltk/build/fltk.sln /p:OutDir=../../../fltk_nuget/lib/native/v120/windesktop/msvcstl/Win32/Release/mt/ /p:Configuration=Release /p:Platform=Win32 /p:PlatformToolset=v120 /p:RuntimeLibrary=MultiThreaded
"C:/Program Files (x86)/MSBuild/14.0/Bin/msbuild.exe" fltk/build/fltk.sln /p:OutDir=../../../fltk_nuget/lib/native/v120/windesktop/msvcstl/Win32/Release/md/ /p:Configuration=Release /p:Platform=Win32 /p:PlatformToolset=v120 /p:RuntimeLibrary=MultiThreadedDLL

"C:/Program Files (x86)/MSBuild/14.0/Bin/msbuild.exe" fltk/build/fltk.sln /p:OutDir=../../../fltk_nuget/lib/native/v120/windesktop/msvcstl/x64/Debug/mt/ /p:Configuration=Debug /p:Platform=x64 /p:PlatformToolset=v120 /p:RuntimeLibrary=MultiThreadedDebug
"C:/Program Files (x86)/MSBuild/14.0/Bin/msbuild.exe" fltk/build/fltk.sln /p:OutDir=../../../fltk_nuget/lib/native/v120/windesktop/msvcstl/x64/Debug/md/ /p:Configuration=Debug /p:Platform=x64 /p:PlatformToolset=v120 /p:RuntimeLibrary=MultiThreadedDebugDLL
"C:/Program Files (x86)/MSBuild/14.0/Bin/msbuild.exe" fltk/build/fltk.sln /p:OutDir=../../../fltk_nuget/lib/native/v120/windesktop/msvcstl/x64/Release/mt/ /p:Configuration=Release /p:Platform=x64 /p:PlatformToolset=v120 /p:RuntimeLibrary=MultiThreaded
"C:/Program Files (x86)/MSBuild/14.0/Bin/msbuild.exe" fltk/build/fltk.sln /p:OutDir=../../../fltk_nuget/lib/native/v120/windesktop/msvcstl/x64/Release/md/ /p:Configuration=Release /p:Platform=x64 /p:PlatformToolset=v120 /p:RuntimeLibrary=MultiThreadedDLL

"C:/Program Files (x86)/MSBuild/14.0/Bin/msbuild.exe" fltk/build/fltk.sln /p:OutDir=../../../fltk_nuget/lib/native/v140/windesktop/msvcstl/Win32/Debug/mt/ /p:Configuration=Debug /p:Platform=Win32 /p:PlatformToolset=v120 /p:RuntimeLibrary=MultiThreadedDebug
"C:/Program Files (x86)/MSBuild/14.0/Bin/msbuild.exe" fltk/build/fltk.sln /p:OutDir=../../../fltk_nuget/lib/native/v140/windesktop/msvcstl/Win32/Debug/md/ /p:Configuration=Debug /p:Platform=Win32 /p:PlatformToolset=v120 /p:RuntimeLibrary=MultiThreadedDebugDLL
"C:/Program Files (x86)/MSBuild/14.0/Bin/msbuild.exe" fltk/build/fltk.sln /p:OutDir=../../../fltk_nuget/lib/native/v140/windesktop/msvcstl/Win32/Release/mt/ /p:Configuration=Release /p:Platform=Win32 /p:PlatformToolset=v120 /p:RuntimeLibrary=MultiThreaded
"C:/Program Files (x86)/MSBuild/14.0/Bin/msbuild.exe" fltk/build/fltk.sln /p:OutDir=../../../fltk_nuget/lib/native/v140/windesktop/msvcstl/Win32/Release/md/ /p:Configuration=Release /p:Platform=Win32 /p:PlatformToolset=v120 /p:RuntimeLibrary=MultiThreadedDLL

"C:/Program Files (x86)/MSBuild/14.0/Bin/msbuild.exe" fltk/build/fltk.sln /p:OutDir=../../../fltk_nuget/lib/native/v140/windesktop/msvcstl/x64/Debug/mt/ /p:Configuration=Debug /p:Platform=x64 /p:PlatformToolset=v140 /p:RuntimeLibrary=MultiThreadedDebug
"C:/Program Files (x86)/MSBuild/14.0/Bin/msbuild.exe" fltk/build/fltk.sln /p:OutDir=../../../fltk_nuget/lib/native/v140/windesktop/msvcstl/x64/Debug/md/ /p:Configuration=Debug /p:Platform=x64 /p:PlatformToolset=v140 /p:RuntimeLibrary=MultiThreadedDebugDLL
"C:/Program Files (x86)/MSBuild/14.0/Bin/msbuild.exe" fltk/build/fltk.sln /p:OutDir=../../../fltk_nuget/lib/native/v140/windesktop/msvcstl/x64/Release/mt/ /p:Configuration=Release /p:Platform=x64 /p:PlatformToolset=v140 /p:RuntimeLibrary=MultiThreaded
"C:/Program Files (x86)/MSBuild/14.0/Bin/msbuild.exe" fltk/build/fltk.sln /p:OutDir=../../../fltk_nuget/lib/native/v140/windesktop/msvcstl/x64/Release/md/ /p:Configuration=Release /p:Platform=x64 /p:PlatformToolset=v140 /p:RuntimeLibrary=MultiThreadedDLL